### ISSUE TITLE
No buckets / Invalid user credentials

### ISSUE THREAD

**Issue by juergschwarz** [kaloyan-raev/hello-storj#9]
Hello storj on Android 6.0
I registered successfully. But i dont see any buckets. If i add a bucket i get error Invalid user credentials.
Filezilla and storj on PC works fine.

**Comment by kaloyan-raev** [comment]
You have set a wrong password. Please, try again importing the key and make sure you specify the correct password.

There is no server-side validation at the moment when importing keys. The user, password and encryption keys are just written to an authentication file that is later used for requesting the bridge server.

It seems the error handling when listing the buckets does not work correctly. Thus, you see "No buckets" instead of "Invalid user credentials". Then when you try to create a new bucket you get the correct error message.

I'll check the error handling when listing buckets ASAP.

**Comment by kaloyan-raev** [comment]
I fixed the issue with the error handling on listing the buckets. Once v0.6.1 is released it will show "Invalid user credentials" instead of "No buckets".

In a future version, I will implement also server-side validation of the provided credentials. See #12.
